Repository tihlde/Lepton, pull requests merged in 2020-11, with the labels that each got.

#195 refactor(registration): refactor registration viewset with exceptions
  app/content/admin/admin.py
  app/content/exceptions.py
  app/content/mixins.py
  app/content/models/event.py
  app/content/models/registration.py
  app/content/permissions/permissions.py
  app/content/views/registration.py
  app/settings.py
  app/tests/conftest.py
  app/tests/test_registration_integration.py
  app/util/exceptions.py
  app/util/mixins.py
Labels: refactor

#201 test(news): add integration tests for news and cleaned up news a bit
  app/content/factories/__init__.py
  app/content/factories/news_factory.py
  app/content/models/news.py
  app/content/serializers/news.py
  app/content/views/news.py
  app/tests/conftest.py
  app/tests/test_news_integration.py
  app/tests/test_registration_integration.py
Labels: refactor, test

#186 fix(registration): Registration queue updated
  app/content/factories/registration_factory.py
  app/content/migrations/0013_add_relative_field_name_in_registartion.py
  app/content/models/event.py
  app/content/models/registration.py
  app/content/tests/test_event_model.py
  app/content/tests/test_registration_model.py
  app/fixture.json
Labels: bug

#184 bug(celery): Refactor mailer and celery function
  app/content/models/event.py
  app/content/models/registration.py
  app/content/signals.py
  app/content/tasks/event.py
  app/content/templates/sign_off_deadline.html
  app/content/views/event.py
  app/content/views/registration.py
  app/tests/test_event_integration.py
  app/tests/test_registration_integration.py
  app/util/mailer.py
  app/util/utils.py
  makefile
Labels: bug
